#version 430

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

//----------------------------------------------------------------------------//

struct Particle
{
	vec3 pos;
	float scale;
};

//----------------------------------------------------------------------------//

layout(std140, binding = 0) buffer Particles
{
	Particle particles[];
};

layout(push_constant) uniform Params
{
    float u_dt;
};

//----------------------------------------------------------------------------//

void main()
{
    //particles[gl_GlobalInvocationID.x].pos.y += 5.0 * u_dt * (float(gl_GlobalInvocationID.x) / 1024.0);
}