#version 430

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

//----------------------------------------------------------------------------//

struct Particle
{
	vec3 pos;
	float scale;
};

//----------------------------------------------------------------------------//

layout(std140, binding = 0) buffer Particles
{
	Particle particles[];
};

//----------------------------------------------------------------------------//

void main()
{
    particles[gl_GlobalInvocationID.x].pos = vec3(gl_GlobalInvocationID.x * 50.0, 150.0, 0.0);
    particles[gl_GlobalInvocationID.x].scale = 20.0;
}